name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    paths:
      - docs/**
jobs:
  update-github-pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install mkdocs-material
      - name: Deploy Pages
        run: |
          git pull
          mkdocs gh-deploy
